site_name: KuroDocs
repo_url: https://github.com/FoliAge-0x76/KuroDocs
plugins:
  - search
  - macros:
      module_name: main
      on_error_fail: true
      on_undefined: strict
  - git-committers:
      repository: FoliAge-0x76/KuroDocs
      branch: master
      docs_path: docs/
nav:
  - 首页: index.md
  - 个人作品集:
    - 个人作品集简介: misc/index.md
    - 奥五报: misc/awb.md
    - Steam 创意工坊项目: misc/workshop.md
    - 画集: misc/illustrations.md
  - 算法学习笔记:
    - 算法笔记简介: algo/index.md
    - 数论:
      - 因数分解技巧: algo/factors.md
      - Möbius 反演: algo/mobius.md
      - Euler 函数: algo/euler_phi.md
    - 多项式:
      - 卷积算法: algo/fft.md
    - 杂项:
      - 2-SAT: algo/2-sat.md
      - SAM: algo/sam.md
  - 音游:
    - 音游部分简介: mug/index.md
  - 魔法编程:
    - Noita 简介: noita/index.md
  - VIPRPG:
    - VIPRPG 简介: viprpg/index.md
    - 王国军·勇者军:
      - 简介: viprpg/kingdom/kingdom.md
    - 魔王军:
      - 简介
    - 安迪德奈伊军:
      - 简介
    - 玉露军:
      - 简介
    - 布莱恩潘曼军:
      - 简介
    - 冥界:
      - 简介
    - 深都:
      - 简介
    - 魔术师协会:
      - 简介: viprpg/magicians/magicians.md
      - 校仓: viprpg/magicians/azekura.md
      - 水门: viprpg/magicians/minaton.md
      - 艾什莉: viprpg/magicians/ashley.md
    - 如果诸神:
      - 简介
  - 苍星:
    - 苍星简介: lapiz/index.md
  - 弹笔:
    - 弹笔简介: flickpen/index.md
  
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
extra_javascript:
  - javascripts/mathjax.js
extra_css:
  - css/fonts.css
  - css/navigation.css
  - css/infobox.css
markdown_extensions:
  - pymdownx.highlight:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
